version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: derogab-cheshire-cat_core_1
      APP_PORT: 80
    
  core:
    image: ghcr.io/cheshire-cat-ai/core:1.6.2
    restart: on-failure
    hostname: ${DEVICE_HOSTNAME}
    user: 1000:1000
    init: true
    volumes:
      - ${APP_DATA_DIR}/data/app-data:/app/cat/data
      - ${APP_DATA_DIR}/data/plugins:/app/cat/plugins
      - ${APP_DATA_DIR}/data/static:/app/cat/static
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
      - LOG_LEVEL=WARNING
